/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TecnicosRouteImport } from './routes/tecnicos'
import { Route as ServicosCncRouteImport } from './routes/servicos-cnc'
import { Route as RequisicoesRouteImport } from './routes/requisicoes'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as MasterRouteImport } from './routes/master'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AtividadesRouteImport } from './routes/atividades'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EstoqueIndexRouteImport } from './routes/estoque.index'
import { Route as MMachineIdRouteImport } from './routes/m.$machineId'
import { Route as EstoqueItemIdRouteImport } from './routes/estoque.$itemId'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnicosRoute = TecnicosRouteImport.update({
  id: '/tecnicos',
  path: '/tecnicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosCncRoute = ServicosCncRouteImport.update({
  id: '/servicos-cnc',
  path: '/servicos-cnc',
  getParentRoute: () => rootRouteImport,
} as any)
const RequisicoesRoute = RequisicoesRouteImport.update({
  id: '/requisicoes',
  path: '/requisicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesRoute = AtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueIndexRoute = EstoqueIndexRouteImport.update({
  id: '/estoque/',
  path: '/estoque/',
  getParentRoute: () => rootRouteImport,
} as any)
const MMachineIdRoute = MMachineIdRouteImport.update({
  id: '/m/$machineId',
  path: '/m/$machineId',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueItemIdRoute = EstoqueItemIdRouteImport.update({
  id: '/estoque/$itemId',
  path: '/estoque/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/orcamentos': typeof OrcamentosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/relatorios': typeof RelatoriosRoute
  '/requisicoes': typeof RequisicoesRoute
  '/servicos-cnc': typeof ServicosCncRoute
  '/tecnicos': typeof TecnicosRoute
  '/termos': typeof TermosRoute
  '/estoque/$itemId': typeof EstoqueItemIdRoute
  '/m/$machineId': typeof MMachineIdRoute
  '/estoque/': typeof EstoqueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/orcamentos': typeof OrcamentosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/relatorios': typeof RelatoriosRoute
  '/requisicoes': typeof RequisicoesRoute
  '/servicos-cnc': typeof ServicosCncRoute
  '/tecnicos': typeof TecnicosRoute
  '/termos': typeof TermosRoute
  '/estoque/$itemId': typeof EstoqueItemIdRoute
  '/m/$machineId': typeof MMachineIdRoute
  '/estoque': typeof EstoqueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/orcamentos': typeof OrcamentosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/relatorios': typeof RelatoriosRoute
  '/requisicoes': typeof RequisicoesRoute
  '/servicos-cnc': typeof ServicosCncRoute
  '/tecnicos': typeof TecnicosRoute
  '/termos': typeof TermosRoute
  '/estoque/$itemId': typeof EstoqueItemIdRoute
  '/m/$machineId': typeof MMachineIdRoute
  '/estoque/': typeof EstoqueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atividades'
    | '/clientes'
    | '/configuracoes'
    | '/financeiro'
    | '/landing'
    | '/login'
    | '/master'
    | '/orcamentos'
    | '/privacidade'
    | '/relatorios'
    | '/requisicoes'
    | '/servicos-cnc'
    | '/tecnicos'
    | '/termos'
    | '/estoque/$itemId'
    | '/m/$machineId'
    | '/estoque/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atividades'
    | '/clientes'
    | '/configuracoes'
    | '/financeiro'
    | '/landing'
    | '/login'
    | '/master'
    | '/orcamentos'
    | '/privacidade'
    | '/relatorios'
    | '/requisicoes'
    | '/servicos-cnc'
    | '/tecnicos'
    | '/termos'
    | '/estoque/$itemId'
    | '/m/$machineId'
    | '/estoque'
  id:
    | '__root__'
    | '/'
    | '/atividades'
    | '/clientes'
    | '/configuracoes'
    | '/financeiro'
    | '/landing'
    | '/login'
    | '/master'
    | '/orcamentos'
    | '/privacidade'
    | '/relatorios'
    | '/requisicoes'
    | '/servicos-cnc'
    | '/tecnicos'
    | '/termos'
    | '/estoque/$itemId'
    | '/m/$machineId'
    | '/estoque/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtividadesRoute: typeof AtividadesRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FinanceiroRoute: typeof FinanceiroRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  MasterRoute: typeof MasterRoute
  OrcamentosRoute: typeof OrcamentosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RelatoriosRoute: typeof RelatoriosRoute
  RequisicoesRoute: typeof RequisicoesRoute
  ServicosCncRoute: typeof ServicosCncRoute
  TecnicosRoute: typeof TecnicosRoute
  TermosRoute: typeof TermosRoute
  EstoqueItemIdRoute: typeof EstoqueItemIdRoute
  MMachineIdRoute: typeof MMachineIdRoute
  EstoqueIndexRoute: typeof EstoqueIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnicos': {
      id: '/tecnicos'
      path: '/tecnicos'
      fullPath: '/tecnicos'
      preLoaderRoute: typeof TecnicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos-cnc': {
      id: '/servicos-cnc'
      path: '/servicos-cnc'
      fullPath: '/servicos-cnc'
      preLoaderRoute: typeof ServicosCncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requisicoes': {
      id: '/requisicoes'
      path: '/requisicoes'
      fullPath: '/requisicoes'
      preLoaderRoute: typeof RequisicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades': {
      id: '/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque/': {
      id: '/estoque/'
      path: '/estoque'
      fullPath: '/estoque/'
      preLoaderRoute: typeof EstoqueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$machineId': {
      id: '/m/$machineId'
      path: '/m/$machineId'
      fullPath: '/m/$machineId'
      preLoaderRoute: typeof MMachineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque/$itemId': {
      id: '/estoque/$itemId'
      path: '/estoque/$itemId'
      fullPath: '/estoque/$itemId'
      preLoaderRoute: typeof EstoqueItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtividadesRoute: AtividadesRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FinanceiroRoute: FinanceiroRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  MasterRoute: MasterRoute,
  OrcamentosRoute: OrcamentosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RelatoriosRoute: RelatoriosRoute,
  RequisicoesRoute: RequisicoesRoute,
  ServicosCncRoute: ServicosCncRoute,
  TecnicosRoute: TecnicosRoute,
  TermosRoute: TermosRoute,
  EstoqueItemIdRoute: EstoqueItemIdRoute,
  MMachineIdRoute: MMachineIdRoute,
  EstoqueIndexRoute: EstoqueIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
